TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

STEAMAPIKEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

REDDIT_CLIENT_ID = "XXXXXXXXXXXXXX"
REDDIT_CLIENT_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
REDDIT_USERNAME = "XXXXXXXX"
REDDIT_PASSWORD = "XXXXXXXX"
REDDIT_USER_AGENT = "XXXXXXXXXX"

COLOR = 0x00ff00

BOTDEVS = (
    '273161070103887872',  # Maik
)
