TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

STEAMAPIKEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

REDDIT_API_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"

COLOR = 0x00ff00

BOTDEVS = (
    '273161070103887872',  # Maik
)
